include_guard(GLOBAL)
# <------------ add more log: verbose and debug
function(tx_log)
	string(JOIN "\n   TXLib: " messageStr ${ARGN})
	message(STATUS "TXLib: ${messageStr}")
endfunction()
function(tx_log_verbose)
	string(JOIN "\n   TXLib: " messageStr ${ARGN})
	message(VERBOSE "TXLib: ${messageStr}")
endfunction()
function(tx_log_debug)
	string(JOIN "\n   TXLib: " messageStr ${ARGN})
	message(DEBUG "TXLib: ${messageStr}")
endfunction()

function(tx_log_error moduleName)
	if(moduleName)
		string(JOIN "\n TXLib:   " messageStr ${ARGN})
		message(FATAL_ERROR " TXLib: In module: [${moduleName}]:\n TXLib:   ${messageStr}")
	else()
		string(JOIN "\n TXLib: " messageStr ${ARGN})
		message(FATAL_ERROR " TXLib: ${messageStr}")
	endif()
endfunction()