include_guard(GLOBAL)

function(tx_log)
	string(JOIN "\nTXLib: " messageStr ${ARGN})
	message(STATUS "TXLib: ${messageStr}")
endfunction()

function(tx_error_log moduleName)
	message(STATUS "a" "b")
	set(NEW_LINE_CHAR "\n")
	if(moduleName)
		string(JOIN "\n TXLib:   " messageStr ${ARGN})
		message(FATAL_ERROR " TXLib: In module: [${moduleName}]:\n TXLib:   ${messageStr}")
	else()
		string(JOIN "\n TXLib: " messageStr ${ARGN})
		message(FATAL_ERROR " TXLib: ${messageStr}")
	endif()
endfunction()